name = "Hina Optimized"
author = "Team Partyhat"
version = "1.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d8ad9dc0b90927b048ff03b88b17ae32e091b4f1cee4d75643cf05e354e1088b"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
